version: '3.8'

networks:
  practice6_main-net:
    external: true

services:
  server:
    image: auth-server:0.0.1
    container_name: auth-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8282:8282'
    depends_on:
      - redis
    networks:
      - practice6_main-net
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./infrastructure/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - '7279:6279'
    networks:
      - practice6_main-net