server:
  port: 8282
spring:
  data:
    redis:
      repositories:
        enabled: true
      database: 0
      host: redis
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/ecommerce_db
    username: ecommerce_user
    password: ecommerce_password
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect