server:
  port: 8282
spring:
  data:
    redis:
      repositories:
        enabled: true
      database: 0
      host: redis
      port: 6379
  #      host: localhost
  #      port: 6379
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/jwt_auth_app_db
    username: dbuser
    password: dbpassword
  #    url: jdbc:postgresql://localhost:5432/jwt_users_db
  #    username: mikholskiy
  #    password: spflmk7q
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect